  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/de/"

  [[main]]
  name = "Posts"
  weight = 400
  identifier = "posts"
  url = "/de/post/"

  [[main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/de/about/"

  [[main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/de/cv/"


  [[footer]]
  name = "Impressum"
  weight = 2
  identifier = "Impressum"
  url = "/de/imprint/"

  [[footer]]
  name = "Datenschutzerklärung"
  weight = 2
  identifier = "Datenschutzerklärung"
  url = "/de/privacy/"
