  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 400
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv/"

  [[footer]]
  name = "Imprint"
  weight = 1
  identifier = "Imprint"
  url = "/imprint/"

  [[footer]]
  name = "Privacy policy"
  weight = 2
  identifier = "Privacy Policy"
  url = "/privacy/"
