
title = "Marlena Müller"
author = "Marlena Müller"
#copyright = "2023"
description = "(she/her) - CS Student"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"



reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true



## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/muller2002/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/marlenalynnann"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@marlena.app"

[[socialIcons]]
icon = "fa fa-fw fa-graduation-cap"
title = "University Paderborn"
url = "https://www.uni-paderborn.de/"

[[socialIcons]]
icon = "fab fa-fw fa-discord"
title = "Discord"
url = "https://discordapp.com/users/Müller#7366"

[mermaid]
# enable = true



